//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Lessons_one
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_order_product
    {
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual t_order t_order { get; set; }
        public virtual t_product t_product { get; set; }
    }
}
